name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: muddukrishna1505/mongodb:v1  #docker build -t roboshop muddukrishna1505/mongodb:v1
    container_name: mongodb #docker run -d --network roboshop muddukrishna1505/mongodb:v1
  catalogue:
    build: ./catalogue
    image: muddukrishna1505/catalogue:v1
    container_name: catalogue
  user:
    build: ./user
    image: muddukrishna1505/user:v1
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
      - redis
      - mongodb
  cart:
    build: ./cart
    image: muddukrishna1505/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
      - redis
      - catalogue  
  redis:
    image: redis:7
    container_name: redis  
  mysql:
    build: ./mysql
    image: muddukrishna1505/mysql:v1
    container_name: mysql   
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
  frontend:
    build: ./frontend
    image: muddukrishna1505/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - mysql
networks:
    default:
      name: roboshop
      driver: bridge
      external: false